CREATE DATABASE sudoku_db;
USE sudoku_db;
CREATE TABLE sudoku_board (
    id INT AUTO_INCREMENT PRIMARY KEY,
    board_state VARCHAR(81) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);